export const produtos = [
    { id: 1, titulo: "Camiseta Azul", descricao: "Camiseta de algodão 100% confortável.", imagem: "produtos/camisa-azul.png", preco: 49.99 },
    { id: 2, titulo: "Tênis Esportivo", descricao: "Tênis para corrida com amortecimento excelente.", imagem: "produtos/tenis-sport.jpeg", preco: 199.99 },
    { id: 3, titulo: "Relógio Digital", descricao: "Relógio resistente à água com várias funções.", imagem: "produtos/relogio-digital.png", preco: 149.99 },
    { id: 4, titulo: "Mochila de Viagem", descricao: "Mochila espaçosa e resistente para viagens.", imagem: "produtos/mochila.png", preco: 89.99 },
    { id: 5, titulo: "Fone de Ouvido", descricao: "Fone de ouvido com cancelamento de ruído.", imagem: "produtos/headset.png", preco: 299.99 },
    { id: 6, titulo: "Smartphone", descricao: "Smartphone com câmera de alta resolução.", imagem: "produtos/mobile.png", preco: 999.99 },
    { id: 7, titulo: "Garrafa Térmica", descricao: "Mantém sua bebida quente ou fria por horas.", imagem: "produtos/garrafa.jpeg", preco: 39.99 },
    { id: 8, titulo: "Livro de Ficção", descricao: "Um romance envolvente e cheio de mistérios.", imagem: "produtos/livro.png", preco: 29.99 },
    { id: 9, titulo: "Cadeira de Escritório", descricao: "Cadeira ergonômica com suporte lombar ajustável.", imagem: "produtos/cadeira-escritorio.jpeg", preco: 499.99 },
    { id: 10, titulo: "Luminária de Mesa", descricao: "Luminária com intensidade de luz ajustável.", imagem: "produtos/luminaria-mesa.jpeg", preco: 59.99 },
    { id: 11, titulo: "Capa de Chuva", descricao: "Capa resistente à água para dias chuvosos.", imagem: "produtos/capa-chuva.jpg", preco: 25.99 },
    { id: 12, titulo: "Mesa Dobrável", descricao: "Ideal para ambientes pequenos e portabilidade.", imagem: "produtos/mesa-dobravel.jpg", preco: 129.99 },
    { id: 13, titulo: "Teclado Mecânico", descricao: "Teclado com iluminação RGB e alta durabilidade.", imagem: "produtos/teclado-mecanico.jpg", preco: 349.99 },
    { id: 14, titulo: "Mouse Gamer", descricao: "Mouse com precisão elevada e design ergonômico.", imagem: "produtos/mouse-gamer.png", preco: 189.99 },
    { id: 15, titulo: "Caneca Personalizada", descricao: "Caneca de cerâmica com estampa criativa.", imagem: "produtos/caneca.png", preco: 19.99 },
    { id: 16, titulo: "Bolsa Feminina", descricao: "Bolsa de couro sintético elegante e espaçosa.", imagem: "produtos/bolsa-feminina.jpg", preco: 119.99 },
    { id: 17, titulo: "Chinelo Confortável", descricao: "Chinelo anatômico para uso diário.", imagem: "produtos/chinelo.png", preco: 29.99 },
    { id: 18, titulo: "Tablet", descricao: "Tablet com tela de alta resolução e grande armazenamento.", imagem: "produtos/tablet.jpg", preco: 1299.99 },
    { id: 19, titulo: "Câmera DSLR", descricao: "Câmera com lente intercambiável para fotografia profissional.", imagem: "produtos/camera-dslr.png", preco: 2499.99 },
    { id: 20, titulo: "Caixa de Som Bluetooth", descricao: "Caixa de som portátil com qualidade de áudio superior.", imagem: "produtos/som.jpg", preco: 299.99 },
    { id: 21, titulo: "Jaqueta de Couro", descricao: "Jaqueta estilosa e resistente ao frio.", imagem: "produtos/jacket.png", preco: 399.99 },
    { id: 22, titulo: "Pulseira Fitness", descricao: "Pulseira inteligente para monitorar atividades físicas.", imagem: "produtos/pulseira.png", preco: 199.99 },
    { id: 23, titulo: "Ventilador de Mesa", descricao: "Ventilador compacto e silencioso.", imagem: "produtos/ventilador-de-mesa.png", preco: 89.99 },
    { id: 24, titulo: "Travesseiro Ortopédico", descricao: "Proporciona conforto e alívio de dores no pescoço.", imagem: "produtos/travesseiro.jpeg", preco: 79.99 },
    { id: 25, titulo: "Fogão Elétrico", descricao: "Compacto e ideal para pequenos ambientes.", imagem: "produtos/fogao-eletrico.png", preco: 299.99 },
    { id: 26, titulo: "Kit de Ferramentas", descricao: "Kit completo com as principais ferramentas para casa.", imagem: "produtos/kit-ferramentas.png", preco: 159.99 },
    { id: 27, titulo: "Console de Videogame", descricao: "Console de última geração para jogos incríveis.", imagem: "produtos/videogame.png", preco: 3499.99 },
    { id: 28, titulo: "Monitor Full HD", descricao: "Monitor de alta qualidade com resolução Full HD.", imagem: "produtos/monitor.png", preco: 899.99 },
    { id: 29, titulo: "Cafeteira Elétrica", descricao: "Prepare café rapidamente e com praticidade.", imagem: "produtos/coffee.png", preco: 219.99 },
    { id: 30, titulo: "Rede de Descanso", descricao: "Rede confortável e fácil de instalar.", imagem: "produtos/rede-descanso.png", preco: 99.99 },
  ];
  